// Centralized Spanish copy. Phase 2 will extract this into messages/es.json +
// messages/en.json for next-intl without touching component logic.

export const copy = {
  brand: "Agentia",
  nav: {
    home: "Inicio",
    login: "Ingresar",
    signup: "Crear cuenta",
    panel: "Panel del agente",
    logout: "Cerrar sesión",
  },
  home: {
    title: "Encontrá al agente inmobiliario ideal",
    subtitle: "Explorá portafolios de agentes verificados en todo Paraguay",
    filters: {
      city: "Ciudad",
      listingType: "Categoría",
      propertyType: "Tipo de Propiedad",
      priceRange: "Rango de precio",
      all: "Todos",
      rent: "Alquiler",
      sale: "Venta",
      clear: "Limpiar filtros",
    },
    agentCard: {
      available: "disponibles",
      sold: "vendidas",
      viewPortfolio: "Ver portafolio",
    },
    empty: "No encontramos agentes con esos filtros. Probá con otra búsqueda.",
  },
  auth: {
    loginTitle: "Ingresá a tu cuenta",
    signupTitle: "Creá tu cuenta",
    chooseRole: "¿Cómo querés registrarte?",
    asAgentIndependent: "Agente",
    asAgentIndependentDesc: "Publicá tu portafolio y recibí leads con tu propia cartera.",
    asAgentExclusive: "Agente Exclusivo",
    asAgentExclusiveDesc: "Prioridad en resultados y leads exclusivos, sin compartir.",
    asUser: "Afiliado",
    asUserDesc: "Generá enlaces de afiliado y ganá 1% de una venta.",
    free: "Gratis",
    perMonth: "/mes",
    email: "Correo electrónico",
    password: "Contraseña",
    username: "Nombre de usuario",
    fullName: "Nombre completo",
    phone: "Teléfono",
    city: "Ciudad",
    ruc: "RUC",
    submitLogin: "Ingresar",
    submitAgent: "Crear cuenta de agente",
    submitUser: "Crear cuenta gratis",
    noAccount: "¿No tenés cuenta?",
    hasAccount: "¿Ya tenés cuenta?",
    confirmEmailTitle: "Te enviamos un e-mail. Confirmá que sos vos.",
    confirmEmailBody: "Abrí el correo que te enviamos y hacé clic en el enlace para activar tu cuenta.",
    confirmEmailCta: "Ir a Ingresar",
  },
  property: {
    price: "Precio",
    location: "Ubicación",
    contactWhatsapp: "Chat",
    share: "Referir",
    shareCopied: "¡Enlace copiado!",
    shareTooltip: "Compartí este enlace en tus canales de venta para aumentar tus posibilidades de ganar 1%.",
    gallery: "Galería",
    sold: "Vendida",
    rented: "Alquilada",
    available: "Disponible",
  },
  chat: {
    greeting: (agentName: string) => `¡Hola! Soy ${agentName}. ¿En qué te puedo ayudar con esta propiedad?`,
    typing: "Escribiendo...",
    inputPlaceholder: "Escribí tu mensaje...",
    send: "Enviar",
    errorReply: "No pude conectarme en este momento. Probá de nuevo en unos minutos.",
  },
  panel: {
    overview: "Resumen",
    dashboardAvailable: "Propiedades disponibles",
    dashboardSold: "Propiedades vendidas",
    dashboardInteractions: "Interacciones",
    dashboardMonthlySales: "Total de ventas del mes",
    dashboardNetIncome: "Balance de ingreso neto",
    downloadMonthlyReport: "Descargar reporte del mes",
    downloadingMonthlyReport: "Generando...",
    vistaGlobal: "Vista Global",
    vistaGlobalSubtitle: "Todas tus métricas del mes, en un solo lugar.",
    statLeads: "Leads",
    statTotalProperties: "Propiedades totales",
    statPortfolioClicks: "Clics en tu portafolio",
    statPropertyClicks: "Clics en propiedades",
    statSolicitudes: "Solicitudes",
    statConversations: "Conversaciones de chat",
    statAgendamientos: "Visitas agendadas",
    statAcuerdosSigned: "Acuerdos firmados",
    statAffiliateClicks: "Clics en enlaces de afiliados",
    statAffiliatesPaid: "Afiliados pagados",
    statRatings: "Valoraciones",
    statMrr: "Ventas cerradas",
    downloadVistaGlobalReport: "Descargar PDF",
    arrReportTitle: "Reporte anual",
    arrReportSubtitle: "Resumen de los últimos 12 meses, con el total facturado.",
    arrReportGenerate: "Generar y descargar reporte ARR",
    arrReportLocked: (days: number) => `Disponible en ${days} ${days === 1 ? "día" : "días"}`,
    properties: "Propiedades",
    newProperty: "Nueva propiedad",
    editProfile: "Editar perfil",
    leads: "Leads",
    subscription: "Suscripción",
    inactiveBanner: "Elegí un plan para que tu portafolio sea visible al público.",
    activateAccount: "Elegí tu plan",
    renewNow: "Renová tu plan",
    statusPending: "Pendiente de pago",
    statusTrialing: "Prueba gratis",
    statusActive: "Activa",
    statusPastDue: "Vencida",
    statusCanceled: "Cancelada",
    leadsEmpty: "Todavía no tenés leads. Compartí tus propiedades para empezar a recibir visitas.",
    directTraffic: "Directo (sin afiliado)",
    referredBy: "Referido por",
    traffic: "Tráfico",
    trafficOrganic: "Orgánico",
    trafficAffiliate: "Enlace Afiliado",
    buyer: "Comprador",
    referralCode: "Código",
    date: "Fecha",
    referralDate: "Fecha de referido",
    referralWindow: "Referido",
    protectedUntil: "Protegido hasta",
    status: "Estado",
    statusCerrado: "Cerrado",
    closeDeal: "Trato cerrado",
    closingDeal: "Cerrando...",
    report: "Reporte",
    downloadReport: "Descargar PDF",
    agreement: "Acuerdo",
    payAffiliate: "Pagar al Afiliado",
    payAffiliateDaysRemaining: (days: number) => `${days}/180 días restantes`,
    commissionPaid: "Pagado",
    sendAliasButton: "Enviar Alias",
    commissionModalTitle: "Calcular comisión",
    salePrice: "Precio de venta",
    commissionDue: "Comisión de afiliado",
    confirmCommission: "Confirmar y pagar comisión",
    confirmingCommission: "Confirmando...",
    chats: "Chats",
    chatsEmpty: "Todavía no tenés conversaciones de chat.",
    chatSummary: "Resumen",
    chatDate: "Fecha",
    chatLead: "Lead",
    viewConversation: "Ver conversación",
    anonymousVisitor: "Visitante anónimo",
    solicitudes: "Solicitudes",
    solicitudesVendedorTitle: "Cliente Vendedor",
    solicitudesCompradorTitle: "Cliente Comprador",
    solicitudesVendedorEmpty: "Todavía no recibiste solicitudes de venta.",
    solicitudesCompradorEmpty: "Todavía no recibiste solicitudes de compra.",
    solicitudesContact: "Contacto",
    solicitudesType: "Tipo",
    solicitudesPrice: "Precio",
    solicitudesPriceRange: "Rango de precio",
    solicitudesDescription: "Descripción",
    solicitudesActions: "Acciones",
    solicitudesApprove: "Aprobar",
    solicitudesReject: "Rechazar",
    solicitudesViewRequest: "Ver solicitud",
    solicitudesView: "Ver",
    solicitudesViewDraft: "Ver borrador",
    solicitudesContactWhatsapp: "Contactar",
    solicitudesReportPending: "El reporte se genera automáticamente cada 15 días.",
    solicitudesSendReport: "Enviar reporte",
    agendamientos: "Agendamientos",
    agendamientosEmpty: "Todavía no tenés visitas agendadas.",
    agendamientosClient: "Cliente",
    agendamientosProperty: "Propiedad",
    agendamientosSchedule: "Día y horario",
    agendamientosStatus: "Estado",
    myAvailability: "Mi Disponibilidad",
    availabilityModalTitle: "Mi Disponibilidad",
    availabilityModalSubtitle: "Elegí los días que atendés visitas y el horario de cada uno.",
    availabilityFrom: "Desde",
    availabilityTo: "Hasta",
    availabilitySave: "Guardar",
    availabilitySaving: "Guardando...",
  },
  affiliatePanel: {
    title: "Panel de afiliado",
    subtitle: "Seguí tus leads referidos y el estado de cada trato.",
    property: "Propiedad",
    agent: "Agente",
    contactAgent: "Contactar al agente",
    whatsappButton: "WhatsApp",
    empty: "Todavía no tenés leads referidos. Compartí una propiedad desde su ficha para empezar.",
    overview: "Resumen",
    myLinks: "Mis Enlaces",
    myLinksSubtitle: "Tus enlaces de afiliado, con la tarjeta de imagen lista para compartir.",
    myLinksEmpty: "Todavía no generaste ningún enlace. Generá uno desde el portafolio de un agente para empezar.",
    image: "Imagen",
    link: "Enlace",
    copyLink: "Copiar",
    linkCopied: "¡Copiado!",
    downloadImage: "Descargar",
    downloadingImage: "Descargando...",
    createdAt: "Generado",
    views: "Vistas",
    leads: "Leads",
    avisos: "Avisos",
    avisosSubtitle: "Te avisamos cuando un agente cierra la venta de una propiedad que promocionaste.",
    avisosEmpty: "Todavía no tenés avisos. Cuando un agente cierre la venta de una propiedad que promocionaste, vas a ver el aviso acá.",
    sold: "Vendida",
    commissionPending: "Pendiente de pago",
    commissionPaid: "Comisión pagada",
  },
  profile: {
    title: "Mi perfil",
    subtitle: "Actualizá tu foto, teléfono y alias.",
    agentSubtitle: "Actualizá tu foto, nombre, teléfono, ciudad y RUC.",
    photo: "Foto de perfil",
    alias: "Alias Bancario",
    phone: "Teléfono",
    fullName: "Nombre completo",
    city: "Ciudad",
    ruc: "RUC",
    save: "Guardar cambios",
    saving: "Guardando...",
    saved: "¡Perfil actualizado!",
  },
  clientRequest: {
    tabVendedor: "Cliente Vendedor",
    tabComprador: "Cliente Comprador",
    vendedorTitle: "Vendé tu propiedad con este agente",
    vendedorSubtitle: "Contanos sobre tu propiedad y el agente se va a poner en contacto.",
    compradorTitle: "¿Buscás comprar una propiedad?",
    compradorSubtitle: "Contanos qué estás buscando y el agente te va a contactar.",
    fullName: "Nombre y Apellido",
    phone: "Teléfono",
    propertyType: "Tipo de Propiedad",
    city: "Ciudad",
    description: "Descripción",
    price: "Precio",
    priceMin: "Precio mínimo",
    priceMax: "Precio máximo",
    commissionDisclaimer: (pct: number) => `Comisión de agente y afiliado: ${pct.toLocaleString("es-PY")}%`,
    submit: "Enviar solicitud",
    submitting: "Enviando...",
    successTitle: "¡Listo!",
    successVendedor: "Le avisamos al agente sobre tu propiedad. Te va a contactar pronto.",
    successComprador: "Le avisamos al agente sobre lo que buscás. Te va a contactar pronto.",
    close: "Cerrar",
  },
} as const;
