// Every Paraguayan municipio, grouped by department below for
// maintainability, exported as one flat sorted list. Sourced from the
// official government list at https://municipios.gov.py/municipios/
// (2026-08-29) — update from that source if it changes.

const CITIES_BY_DEPARTMENT: Record<string, string[]> = {
  Capital: ["Asunción"],
  Central: [
    "Areguá",
    "Capiatá",
    "Fernando de la Mora",
    "Guarambaré",
    "Itá",
    "Itauguá",
    "J. Augusto Saldívar",
    "Lambaré",
    "Limpio",
    "Luque",
    "Mariano Roque Alonso",
    "Ñemby",
    "Nueva Italia",
    "San Antonio",
    "San Lorenzo",
    "Villa Elisa",
    "Villeta",
    "Ypacaraí",
    "Ypané",
  ],
  "Alto Paraná": [
    "Ciudad del Este",
    "Doctor Juan León Mallorquín",
    "Doctor Raúl Peña",
    "Domingo Martínez de Irala",
    "Hernandarias",
    "Iruña",
    "Itakyry",
    "Juan Emilio O'Leary",
    "Los Cedrales",
    "Mbaracayú",
    "Minga Guazú",
    "Minga Porá",
    "Naranjal",
    "Ñacunday",
    "Presidente Franco",
    "San Alberto",
    "San Cristóbal",
    "Santa Fe del Paraná",
    "Santa Rita",
    "Santa Rosa del Monday",
    "Tavapy",
    "Yguazú",
  ],
  Itapúa: [
    "Alto Vera",
    "Bella Vista",
    "Cambyretá",
    "Capitán Meza",
    "Capitán Miranda",
    "Carlos Antonio López",
    "Carmen del Paraná",
    "Coronel Bogado",
    "Edelira",
    "Encarnación",
    "Fram",
    "General José María Delgado",
    "Gral. Artigas",
    "Hohenau",
    "Itapúa Poty",
    "Jesús de Tavarangué",
    "José Leandro Oviedo",
    "La Paz",
    "Mayor Otaño",
    "Natalio",
    "Nueva Alborada",
    "Obligado",
    "Pirapo",
    "San Cosme y Damián",
    "San Juan del Paraná",
    "San Pedro del Paraná",
    "San Rafael del Paraná",
    "Tomás R. Pereira",
    "Trinidad",
    "Yatytay",
  ],
  Caaguazú: [
    "3 de Febrero",
    "Caaguazú",
    "Carayao",
    "Coronel Oviedo",
    "Dr. Cecilio Báez",
    "Dr. J. Eulogio Estigarribia",
    "Dr. Juan Manuel Frutos",
    "José Domingo Ocampos",
    "La Pastora",
    "Mcal. Francisco Solano López",
    "Nueva Londres",
    "Nueva Toledo",
    "R.I. 3 Corrales",
    "Raúl Arsenio Oviedo",
    "Repatriación",
    "San Joaquín",
    "San José de los Arroyos",
    "Santa Rosa del Mbutuy",
    "Simón Bolívar",
    "Tembiapora",
    "Vaquería",
    "Yhú",
  ],
  "San Pedro": [
    "25 de Diciembre",
    "Antequera",
    "Capiibary",
    "Choré",
    "Gral. Elizardo Aquino",
    "Gral. Resquín",
    "Guayaibí",
    "Itacurubí del Rosario",
    "Liberación",
    "Lima",
    "Nueva Germania",
    "San Estanislao",
    "San José del Rosario",
    "San Pablo",
    "San Pedro del Ycuamandyyú",
    "San Vicente Pancholo",
    "Santa Rosa del Aguaray",
    "Tacuatí",
    "Unión",
    "Villa del Rosario",
    "Yataity del Norte",
    "Yrybucuá",
  ],
  Cordillera: [
    "Altos",
    "Arroyos y Esteros",
    "Atyrá",
    "Caacupé",
    "Caraguatay",
    "Emboscada",
    "Eusebio Ayala",
    "Isla Pucú",
    "Itacurubí de la Cordillera",
    "Juan de Mena",
    "Loma Grande",
    "Mbocayaty del Yhaguy",
    "Nueva Colombia",
    "Piribebuy",
    "Primero de Marzo",
    "San Bernardino",
    "San José Obrero",
    "Santa Elena",
    "Tobatí",
    "Valenzuela",
  ],
  Guairá: [
    "Borja",
    "Coronel Martínez",
    "Doctor Bottrell",
    "Eugenio A. Garay",
    "Félix Pérez Cardozo",
    "Independencia",
    "Itapé",
    "Iturbe",
    "José Fassardi",
    "José Mauricio Troche",
    "Mbocayaty del Guairá",
    "Natalicio Talavera",
    "Ñumí",
    "Paso Yobái",
    "San Salvador",
    "Tebicuary",
    "Villarrica",
    "Yataity",
  ],
  Caazapá: [
    "3 de Mayo",
    "Abaí",
    "Buena Vista",
    "Caazapá",
    "Coronel Maciel",
    "Doctor Moisés S. Bertoni",
    "Fulgencio Yegros",
    "General Higinio Morínigo",
    "San Juan Nepomuceno",
    "Tavaí",
    "Yuty",
  ],
  Misiones: [
    "Ayolas",
    "San Ignacio Guazú",
    "San Juan Bautista",
    "San Miguel",
    "San Patricio",
    "Santa María de Fe",
    "Santa Rosa Misiones",
    "Santiago",
    "Villa Florida",
    "Yabebyry",
  ],
  Paraguarí: [
    "Acahay",
    "Caapucú",
    "Carapeguá",
    "Escobar",
    "Gral. Bernardino Caballero",
    "La Colmena",
    "María Antonia",
    "Mbuyapey",
    "Paraguarí",
    "Pirayú",
    "Quiindy",
    "Quyquyhó",
    "San Roque González de Santa Cruz",
    "Sapucai",
    "Tebicuarymí",
    "Yaguarón",
    "Ybycuí",
    "Ybytymí",
  ],
  "Presidente Hayes": [
    "Benjamín Aceval",
    "Campo Aceval",
    "Gral. José María Brúguez",
    "José Falcón",
    "Nanawa",
    "Nueva Asunción",
    "Puerto Pinasco",
    "Tte. 1ro Manuel Irala Fernández",
    "Tte. Esteban Martínez",
    "Villa Hayes",
  ],
  Ñeembucú: [
    "Alberdi",
    "Cerrito",
    "Desmochados",
    "Gral. José E. Díaz",
    "Guazúcuá",
    "Humaitá",
    "Isla Umbú",
    "Laureles",
    "Mayor José D. Martínez",
    "Paso de Patria",
    "Pilar",
    "San Juan Bautista del Ñeembucú",
    "Tacuaras",
    "Villa Franca",
    "Villa Oliva",
    "Villalbín",
  ],
  Canindeyú: [
    "Corpus Christi",
    "Curuguaty",
    "Gral. Francisco Caballero Álvarez",
    "Itanará",
    "Katueté",
    "La Paloma",
    "Laurel",
    "Maracaná",
    "Nueva Esperanza",
    "Puerto Adela",
    "Salto del Guairá",
    "Villa Ygatimí",
    "Ybyrarobaná",
    "Yby Pytá",
    "Ypejhú",
    "Yasy Cañy",
  ],
  Boquerón: ["Boquerón", "Filadelfia", "Loma Plata", "Mariscal José Félix Estigarribia"],
  "Alto Paraguay": ["Bahía Negra", "Capitán Carmelo Peralta", "Fuerte Olimpo", "Puerto Casado"],
  Amambay: [
    "Bella Vista Norte",
    "Capitán Bado",
    "Cerro Corá",
    "Karapaí",
    "Pedro Juan Caballero",
    "Zanja Pytá",
  ],
  Concepción: [
    "Arroyito",
    "Azote'y",
    "Belén",
    "Concepción",
    "Horqueta",
    "Loreto",
    "Paso Barreto",
    "Paso Horqueta",
    "San Alfredo",
    "San Carlos del Apa",
    "San Lázaro",
    "Sargento José Félix López",
    "Yby Ya'ú",
  ],
};

export const CITY_OPTIONS = Array.from(new Set(Object.values(CITIES_BY_DEPARTMENT).flat())).sort((a, b) =>
  a.localeCompare(b, "es")
);
