// Paraguay's district capitals and major cities/localities, grouped by
// department below for maintainability, exported as one flat sorted list.

const CITIES_BY_DEPARTMENT: Record<string, string[]> = {
  Capital: ["Asunción"],
  Central: [
    "Areguá",
    "Capiatá",
    "Fernando de la Mora",
    "Guarambaré",
    "Itá",
    "Itauguá",
    "J. Augusto Saldívar",
    "Lambaré",
    "Limpio",
    "Luque",
    "Mariano Roque Alonso",
    "Ñemby",
    "Nueva Italia",
    "San Antonio",
    "San Lorenzo",
    "Villa Elisa",
    "Villeta",
    "Ypacaraí",
    "Ypané",
  ],
  "Alto Paraná": [
    "Ciudad del Este",
    "Domingo Martínez de Irala",
    "Hernandarias",
    "Juan León Mallorquín",
    "Los Cedrales",
    "Minga Guazú",
    "Naranjal",
    "Presidente Franco",
    "Santa Rita",
  ],
  Itapúa: [
    "Encarnación",
    "Bella Vista",
    "Cambyretá",
    "Capitán Miranda",
    "Carmen del Paraná",
    "Coronel Bogado",
    "Fram",
    "Hohenau",
    "Jesús",
    "Nueva Alborada",
    "Obligado",
    "San Rafael del Paraná",
    "Trinidad",
  ],
  Caaguazú: [
    "Coronel Oviedo",
    "Caaguazú",
    "Cecilio Báez",
    "Dr. Juan Manuel Frutos",
    "Nueva Londres",
    "Raúl Arsenio Oviedo",
    "Repatriación",
    "Simón Bolívar",
    "Yhú",
  ],
  "San Pedro": [
    "San Pedro del Ycuamandiyú",
    "Choré",
    "Guayaybí",
    "San Estanislao",
    "Santa Rosa del Aguaray",
    "Villa del Rosario",
  ],
  Cordillera: [
    "Caacupé",
    "Altos",
    "Arroyos y Esteros",
    "Atyrá",
    "Caraguatay",
    "Emboscada",
    "Eusebio Ayala",
    "Piribebuy",
    "San Bernardino",
    "Tobatí",
  ],
  Guairá: [
    "Villarrica",
    "Borja",
    "Colonia Independencia",
    "Itapé",
    "Iturbe",
    "Mbocayaty",
    "Paso Yobái",
    "San Salvador",
  ],
  Caazapá: ["Caazapá", "Abaí", "Buena Vista", "General Higinio Morínigo", "San Juan Nepomuceno", "Yuty"],
  Misiones: ["San Juan Bautista", "Ayolas", "San Ignacio", "San Miguel", "Santa María", "Santiago", "Villa Florida"],
  Paraguarí: [
    "Paraguarí",
    "Acahay",
    "Caapucú",
    "La Colmena",
    "Pirayú",
    "Quiindy",
    "Ybycuí",
    "Yaguarón",
  ],
  "Presidente Hayes": ["Villa Hayes", "Benjamín Aceval", "Nanawa", "Puerto Pinasco"],
  Ñeembucú: ["Pilar", "Alberdi", "Humaitá", "Villa Franca", "Villa Oliva"],
  Canindeyú: ["Salto del Guairá", "Curuguaty", "Katueté", "Ygatimí", "Nueva Esperanza"],
  Boquerón: ["Filadelfia", "Loma Plata", "Mariscal Estigarribia"],
  "Alto Paraguay": ["Fuerte Olimpo", "Bahía Negra", "Carmelo Peralta"],
};

export const CITY_OPTIONS = Array.from(new Set(Object.values(CITIES_BY_DEPARTMENT).flat())).sort((a, b) =>
  a.localeCompare(b, "es")
);
